language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - templates/webdesign/node_modules
before_script:
- openssl aes-256-cbc -K $encrypted_ec18ff5626c0_key -iv $encrypted_ec18ff5626c0_iv
  -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- travis_retry eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- |
  if [ false != "$TRAVIS_PULL_REQUEST" ]; then
    travis_retry npm install
    npm run build
    cd templates/webdesign
    travis_retry npm install
    npm run build
    cd ../..
  fi
after_success:
- |
  if [ false == "$TRAVIS_PULL_REQUEST" ] && [ "master" == "$TRAVIS_BRANCH" ]; then
    bash ./.travis/master.sh
  fi
- |
  if [ false != "$TRAVIS_PULL_REQUEST" ]; then
    bash ./.travis/pr.sh
  fi
notifications:
  email: false
